services:
  session:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.ros2}
    image: ${IMAGE_NAME:-ros2_novnc_desktop:jazzy}
    container_name: ${CONTAINER_NAME:-default_session}
    network_mode: host
    shm_size: '512mb'
    environment:
      - SESSION_ID=${SESSION_ID:-1}
      - CONTAINER_NAME=${CONTAINER_NAME:-default_session}
      - ROS_DOMAIN_ID=0
