FROM ros:jazzy

ENV DEBIAN_FRONTEND=noninteractive

# 描画スタックおよびnoVNC関連ツールのAPT一括インストール
RUN apt-get update && apt-get install -y \
    ros-jazzy-desktop \
    tigervnc-standalone-server \
    fluxbox \
    lxterminal \
    novnc \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh \
    && echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

ENTRYPOINT ["/entrypoint.sh"]
