FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# 描画スタックおよびnoVNC関連ツールのAPT一括インストール
RUN apt-get update && apt-get install -y \
    tigervnc-standalone-server \
    fluxbox \
    lxterminal \
    novnc \
    net-tools \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
